// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TequilasRestaurant.Data;

#nullable disable

namespace TequilasRestaurant.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260301121242_ChangedUserIdType")]
    partial class ChangedUserIdType
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasDiscriminator().HasValue("IdentityUser");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("TequilasRestaurant.Models.DbModels.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Description = "Безалкогольні та алкогольні напої різних видів",
                            Name = "Напої"
                        },
                        new
                        {
                            CategoryId = 2,
                            Description = "Хлібобулочні та кондитерські вироби",
                            Name = "Випічка"
                        },
                        new
                        {
                            CategoryId = 3,
                            Description = "Молоко, сири, йогурти та інші молочні вироби",
                            Name = "Молочні продукти"
                        },
                        new
                        {
                            CategoryId = 4,
                            Description = "Свіже м’ясо, ковбаси та м’ясні напівфабрикати",
                            Name = "М’ясні продукти"
                        },
                        new
                        {
                            CategoryId = 5,
                            Description = "Свіжа риба, морепродукти та рибні делікатеси",
                            Name = "Рибні продукти"
                        },
                        new
                        {
                            CategoryId = 6,
                            Description = "Свіжі сезонні овочі",
                            Name = "Овочі"
                        },
                        new
                        {
                            CategoryId = 7,
                            Description = "Свіжі фрукти та ягоди",
                            Name = "Фрукти"
                        },
                        new
                        {
                            CategoryId = 8,
                            Description = "Крупи, макаронні вироби та бобові",
                            Name = "Крупи та макарони"
                        },
                        new
                        {
                            CategoryId = 9,
                            Description = "Цукерки, шоколад, печиво та десерти",
                            Name = "Солодощі"
                        },
                        new
                        {
                            CategoryId = 10,
                            Description = "Заморожені овочі, напівфабрикати та морозиво",
                            Name = "Заморожені продукти"
                        },
                        new
                        {
                            CategoryId = 11,
                            Description = "Соуси, приправи та спеції",
                            Name = "Соуси та спеції"
                        },
                        new
                        {
                            CategoryId = 12,
                            Description = "Овочеві, м’ясні та рибні консерви",
                            Name = "Консерви"
                        });
                });

            modelBuilder.Entity("TequilasRestaurant.Models.DbModels.Ingredient", b =>
                {
                    b.Property<int>("IngredientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IngredientId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IngredientId");

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            IngredientId = 1,
                            Description = "Мелена кава з зерен арабіки",
                            Name = "Кава арабіка"
                        },
                        new
                        {
                            IngredientId = 2,
                            Description = "Коров’яче молоко для кавових напоїв",
                            Name = "Молоко"
                        },
                        new
                        {
                            IngredientId = 3,
                            Description = "Білий кристалічний цукор",
                            Name = "Цукор"
                        },
                        new
                        {
                            IngredientId = 4,
                            Description = "Пшеничне борошно",
                            Name = "Борошно"
                        },
                        new
                        {
                            IngredientId = 5,
                            Description = "Натуральне вершкове масло",
                            Name = "Вершкове масло"
                        },
                        new
                        {
                            IngredientId = 6,
                            Description = "Пекарські дріжджі",
                            Name = "Дріжджі"
                        },
                        new
                        {
                            IngredientId = 7,
                            Description = "М’ясо яловичини",
                            Name = "Яловичина"
                        },
                        new
                        {
                            IngredientId = 8,
                            Description = "Філе курячої грудки",
                            Name = "Куряче філе"
                        },
                        new
                        {
                            IngredientId = 9,
                            Description = "Філе лосося",
                            Name = "Лосось"
                        },
                        new
                        {
                            IngredientId = 10,
                            Description = "Паста з твердих сортів пшениці",
                            Name = "Паста"
                        },
                        new
                        {
                            IngredientId = 11,
                            Description = "Копчений бекон",
                            Name = "Бекон"
                        },
                        new
                        {
                            IngredientId = 12,
                            Description = "Вершки для соусів",
                            Name = "Вершки"
                        },
                        new
                        {
                            IngredientId = 13,
                            Description = "Курячі яйця",
                            Name = "Яйця"
                        },
                        new
                        {
                            IngredientId = 14,
                            Description = "Темний шоколад",
                            Name = "Шоколад"
                        },
                        new
                        {
                            IngredientId = 15,
                            Description = "Асорті свіжих фруктів",
                            Name = "Фрукти"
                        },
                        new
                        {
                            IngredientId = 16,
                            Description = "Сезонні овочі",
                            Name = "Овочі"
                        },
                        new
                        {
                            IngredientId = 17,
                            Description = "Оливкова олія першого віджиму",
                            Name = "Оливкова олія"
                        },
                        new
                        {
                            IngredientId = 18,
                            Description = "Кухонна харчова сіль",
                            Name = "Сіль"
                        });
                });

            modelBuilder.Entity("TequilasRestaurant.Models.DbModels.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("OrderId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("TequilasRestaurant.Models.DbModels.OrderItem", b =>
                {
                    b.Property<int>("OrderItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderItemId"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("OrderItemId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("TequilasRestaurant.Models.DbModels.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryId = 1,
                            Description = "Класичний еспресо",
                            ImageUrl = "https://placehold.co/600x400",
                            Name = "Еспресо",
                            Price = 45.00m,
                            Stock = 100
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryId = 1,
                            Description = "Кава з молочною пінкою",
                            ImageUrl = "https://placehold.co/600x400",
                            Name = "Капучино",
                            Price = 65.00m,
                            Stock = 80
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryId = 2,
                            Description = "Свіжа італійська чіабата",
                            ImageUrl = "https://placehold.co/600x400",
                            Name = "Чіабата",
                            Price = 35.00m,
                            Stock = 40
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryId = 2,
                            Description = "Теплий круасан з вершковим маслом",
                            ImageUrl = "https://placehold.co/600x400",
                            Name = "Круасан з маслом",
                            Price = 55.00m,
                            Stock = 30
                        },
                        new
                        {
                            ProductId = 5,
                            CategoryId = 3,
                            Description = "Асорті твердих і м’яких сирів",
                            ImageUrl = "https://placehold.co/600x400",
                            Name = "Сирна тарілка",
                            Price = 180.00m,
                            Stock = 20
                        },
                        new
                        {
                            ProductId = 6,
                            CategoryId = 4,
                            Description = "Стейк середньої прожарки",
                            ImageUrl = "https://placehold.co/600x400",
                            Name = "Стейк з яловичини",
                            Price = 420.00m,
                            Stock = 15
                        },
                        new
                        {
                            ProductId = 7,
                            CategoryId = 4,
                            Description = "Філе курки на грилі",
                            ImageUrl = "https://placehold.co/600x400",
                            Name = "Куряче філе гриль",
                            Price = 220.00m,
                            Stock = 25
                        },
                        new
                        {
                            ProductId = 8,
                            CategoryId = 5,
                            Description = "Філе лосося з лимоном",
                            ImageUrl = "https://placehold.co/600x400",
                            Name = "Лосось на грилі",
                            Price = 380.00m,
                            Stock = 12
                        },
                        new
                        {
                            ProductId = 9,
                            CategoryId = 6,
                            Description = "Асорті сезонних овочів",
                            ImageUrl = "https://placehold.co/600x400",
                            Name = "Овочі гриль",
                            Price = 160.00m,
                            Stock = 30
                        },
                        new
                        {
                            ProductId = 10,
                            CategoryId = 7,
                            Description = "Асорті свіжих фруктів",
                            ImageUrl = "https://placehold.co/600x400",
                            Name = "Фруктова тарілка",
                            Price = 140.00m,
                            Stock = 18
                        },
                        new
                        {
                            ProductId = 11,
                            CategoryId = 8,
                            Description = "Паста з беконом і вершковим соусом",
                            ImageUrl = "https://placehold.co/600x400",
                            Name = "Паста Карбонара",
                            Price = 260.00m,
                            Stock = 22
                        },
                        new
                        {
                            ProductId = 12,
                            CategoryId = 9,
                            Description = "Десерт з рідкою шоколадною начинкою",
                            ImageUrl = "https://placehold.co/600x400",
                            Name = "Шоколадний фондан",
                            Price = 150.00m,
                            Stock = 20
                        },
                        new
                        {
                            ProductId = 13,
                            CategoryId = 11,
                            Description = "Домашній соус барбекю",
                            ImageUrl = "https://placehold.co/600x400",
                            Name = "Соус BBQ",
                            Price = 40.00m,
                            Stock = 50
                        });
                });

            modelBuilder.Entity("TequilasRestaurant.Models.DbModels.ProductIngredient", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("IngredientId")
                        .HasColumnType("int");

                    b.HasKey("ProductId", "IngredientId");

                    b.HasIndex("IngredientId");

                    b.ToTable("ProductIngredients");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            IngredientId = 1
                        },
                        new
                        {
                            ProductId = 1,
                            IngredientId = 3
                        },
                        new
                        {
                            ProductId = 2,
                            IngredientId = 1
                        },
                        new
                        {
                            ProductId = 2,
                            IngredientId = 2
                        },
                        new
                        {
                            ProductId = 2,
                            IngredientId = 3
                        },
                        new
                        {
                            ProductId = 3,
                            IngredientId = 4
                        },
                        new
                        {
                            ProductId = 3,
                            IngredientId = 5
                        },
                        new
                        {
                            ProductId = 3,
                            IngredientId = 6
                        },
                        new
                        {
                            ProductId = 3,
                            IngredientId = 18
                        },
                        new
                        {
                            ProductId = 4,
                            IngredientId = 4
                        },
                        new
                        {
                            ProductId = 4,
                            IngredientId = 5
                        },
                        new
                        {
                            ProductId = 4,
                            IngredientId = 6
                        },
                        new
                        {
                            ProductId = 4,
                            IngredientId = 18
                        },
                        new
                        {
                            ProductId = 5,
                            IngredientId = 2
                        },
                        new
                        {
                            ProductId = 5,
                            IngredientId = 13
                        },
                        new
                        {
                            ProductId = 6,
                            IngredientId = 7
                        },
                        new
                        {
                            ProductId = 6,
                            IngredientId = 18
                        },
                        new
                        {
                            ProductId = 7,
                            IngredientId = 8
                        },
                        new
                        {
                            ProductId = 7,
                            IngredientId = 18
                        },
                        new
                        {
                            ProductId = 8,
                            IngredientId = 9
                        },
                        new
                        {
                            ProductId = 8,
                            IngredientId = 18
                        },
                        new
                        {
                            ProductId = 9,
                            IngredientId = 16
                        },
                        new
                        {
                            ProductId = 9,
                            IngredientId = 17
                        },
                        new
                        {
                            ProductId = 9,
                            IngredientId = 18
                        },
                        new
                        {
                            ProductId = 10,
                            IngredientId = 15
                        },
                        new
                        {
                            ProductId = 10,
                            IngredientId = 3
                        },
                        new
                        {
                            ProductId = 11,
                            IngredientId = 10
                        },
                        new
                        {
                            ProductId = 11,
                            IngredientId = 11
                        },
                        new
                        {
                            ProductId = 11,
                            IngredientId = 12
                        },
                        new
                        {
                            ProductId = 11,
                            IngredientId = 13
                        },
                        new
                        {
                            ProductId = 11,
                            IngredientId = 18
                        },
                        new
                        {
                            ProductId = 12,
                            IngredientId = 14
                        },
                        new
                        {
                            ProductId = 12,
                            IngredientId = 13
                        },
                        new
                        {
                            ProductId = 12,
                            IngredientId = 5
                        },
                        new
                        {
                            ProductId = 12,
                            IngredientId = 3
                        },
                        new
                        {
                            ProductId = 13,
                            IngredientId = 17
                        },
                        new
                        {
                            ProductId = 13,
                            IngredientId = 18
                        });
                });

            modelBuilder.Entity("TequilasRestaurant.Models.DbModels.ApplicationUser", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.HasDiscriminator().HasValue("ApplicationUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TequilasRestaurant.Models.DbModels.Order", b =>
                {
                    b.HasOne("TequilasRestaurant.Models.DbModels.ApplicationUser", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TequilasRestaurant.Models.DbModels.OrderItem", b =>
                {
                    b.HasOne("TequilasRestaurant.Models.DbModels.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TequilasRestaurant.Models.DbModels.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("TequilasRestaurant.Models.DbModels.Product", b =>
                {
                    b.HasOne("TequilasRestaurant.Models.DbModels.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("TequilasRestaurant.Models.DbModels.ProductIngredient", b =>
                {
                    b.HasOne("TequilasRestaurant.Models.DbModels.Ingredient", "Ingredient")
                        .WithMany("ProductIngredients")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TequilasRestaurant.Models.DbModels.Product", "Product")
                        .WithMany("ProductIngredients")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("TequilasRestaurant.Models.DbModels.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("TequilasRestaurant.Models.DbModels.Ingredient", b =>
                {
                    b.Navigation("ProductIngredients");
                });

            modelBuilder.Entity("TequilasRestaurant.Models.DbModels.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("TequilasRestaurant.Models.DbModels.Product", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("ProductIngredients");
                });

            modelBuilder.Entity("TequilasRestaurant.Models.DbModels.ApplicationUser", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
